### ISSUE TITLE
Can't withdraw or send tips

### ISSUE THREAD

**Issue by dylie** [expanse-org/discord-tip-bot#3]
Hey there,

when sending tips the bot replies with 'Could not find user, please try another one' even if i do @username. 

When I withdraw it gives an 'private key length' error in console? Any idea how to fix?

Thx!

**Comment by dinc334** [comment]
Did you register user before?

**Comment by dylie** [comment]
Yes, I have 2 registered users up for testing.

**Comment by dinc334** [comment]
And user have "username" name?

**Comment by dylie** [comment]
The users are Normal discord names, the ones you can @username. Maybe chat with me over Discord if that’s easier?

**Comment by dinc334** [comment]
Ok, you can contact me in Expanse discord as a @speedrunner
